//when adding new parameters, follow the below template (replace <description> with appropriate string)
//P("<human-readable name>, <data type>, <variable name>, <parameter name (within conf/floats.yml)>, <count (increasing)>")
P("MASS", double, mass, "param_mass", 0)
P("FRICTION", double, friction, "param_friction", 1)
P("COMPLIANCE", double, compliance, "param_compliance", 2)
//P("MASS_0_FRICTION_0: ", double, m0f0, 0, 0)   
//P("MASS_1_FRICTION_0: ", double, m1f0, P1, 1)   
//P("MASS_2_FRICTION_0: ", double, m2f0, P2, 2)   
//P("MASS_3_FRICTION_0: ", double, m3f0, 3, 1)   
/*
P("MASS_4_FRICTION_0: ", double, m4f0, P4, 4)   
P("MASS_5_FRICTION_0: ", double, m5f0, P5, 5)   
P("MASS_6_FRICTION_0: ", double, m6f0, P6, 6)   
P("MASS_7_FRICTION_0: ", double, m7f0, P7, 7)   
P("MASS_8_FRICTION_0: ", double, m8f0, P8, 8)   
P("MASS_9_FRICTION_0: ", double, m9f0, P9, 9)   
*/
