X(Playing, 'i', false,      "Initialize Motion")
X(PLAYING, 'p', false,      "Play")
X(PAUSED,  'a', loop_flag,  "Pause")
X(STOPPED, 's', false,      "Stop")
X(LOOPING, 'l', true,       "Loop")
X(QUIT,    'q', false,      "Quit")
